initnames=c("Y","E_b","D_h","E_fk","YD","V_h")
inits<-array(data=NA, dim=c(1,length(initnames)),dimnames = list(NULL,initnames))
parnames=c("alpha1","alpha2","theta","w","delta","r_d","mu1","mu2","r_0","iota1","iota2","lambda1","kappa","chi","beta1","beta2","gamma","expdyn","opt","pes","epsilon","eta","rho","tau","lambda2","gov","phi_g","phi_b1","bank","sigma","omega","fshare","types1","fulloutput","CAR","kappa_L","divpol","types2","phi_b2","phi_div")
params<-array(data=NA, dim=c(1,length(parnames)),dimnames = list(NULL,parnames))
nF=50
firminitnames=c("k","K","L","r_L","D_f","C","E_fc","yield")
  
firminits<-array(data=NA,dim=c(nF,length(firminitnames)),dimnames=list(NULL,firminitnames))
init=function(init=inits,param=params,firminit=firminits,calib=calib){
  nF=50
  share<-c(rep(1/nF,nF))
  k_agg=calib$k_agg
  k=k_agg*share
  w=calib$w
  u=calib$u
  kappa=calib$kappa
  c=u*kappa*k_agg
  kappa_L=calib$kappa_L
  omega=calib$omega
  omega_c=omega
  p_k=(1+omega)*w
  K_agg=k_agg*p_k
  K=K_agg*share
  delta=calib$delta
  p_c=(1+omega)*w
  i_agg=delta*k_agg
  W_k=w*i_agg
  y=c+i_agg
  i=i_agg/nF
  c_dagg=c
  c_d=c_dagg*share
  Y=c_dagg*p_c+i_agg*p_k
  C=share*p_c*c_dagg
  N_dc=c_dagg
  N_dc=c_dagg+kappa_L*kappa*k_agg*(1-delta)
  W_cagg=N_dc*w
  W_c=W_cagg*share
  CF=C-W_c
  YD=c_dagg*p_c
  YD_e=YD
  Lev=calib$Lev
  L_agg=Lev*K_agg
  L=share*L_agg
  r_0=calib$r_0
  theta=delta
  gamma=calib$gamma
  int=i*p_k-theta*L+gamma*CF
  gap=C-W_c-theta*L-gamma*CF
  r_L=(gap-(int-gamma*CF))/L
  mu2=(-CF*r_0+CF*r_L)/((L-theta*L+p_k*i-(int-gamma*CF))*(r_L+theta))
  mu2=mean(mu2)
  Q=C-W_c
  CAR=calib$CAR
  E_b=CAR*L_agg
  E_fk=0
  D=L_agg-E_b
  D_f=0
  D_h=D-sum(D_f)
  E_fc=K+D_f-L
  alpha1=calib$alpha1
  alpha2=(YD-alpha1*YD)/(D_h+E_b+sum(E_fc))
  V_h=D_h+sum(E_fc)+E_b
  lambda1=calib$lambda1
  iota1=calib$iota1
  iota2=calib$iota2
  chi=calib$chi
  Div_b=mean(r_L)*sum(L)
  Div_fk=i_agg*p_k-W_k
  Pr_fc=C-W_c-i*p_k+(K-delta*k*p_k+i*p_k-K)-r_L*L
  Div_fc=Pr_fc
  beta1=mean((r_L*L+theta*L)/CF)
  beta2=calib$beta2
  r_d=r_0
  rev=Q/delta
  yield=rev/(1+r_d/delta)
  p_ks=p_k+(1-(int-gamma*CF)/(i*p_k))*r_L/(theta+r_d)*p_k
  mu1=-((p_k+(1-(int-gamma*CF)/(i*p_k))*r_L/(theta+r_d)*p_k)*(k-delta*k)-yield)/((i*p_k)^2)
  p_dk=(yield-mu1*(i*p_k)^2)/(k-delta*k)
  p_dkint=(yield-mu1*(int-gamma*CF)^2)/(k-delta*k)
  mu1=mean(mu1)
  meanlev=mean(K/E_fc)
  expdyn=0
  opt=1.1
  pes=0.9
  epsilon=calib$epsilon
  eta=-50
  rho=0.5
  tau=calib$tau
  lambda2=calib$lambda2
  gov=0
  phi_g=1
  phi_b1=0.6
  bank=0
  sigma=calib$sigma
  fshare=0.5
  types1=0
  types2=0
  fulloutput=1
  divpol=0
  phi_b2=0.9
  phi_div=8

  init[1,1]<-Y
  init[1,2]<-E_b
  init[1,3]<-D_h
  init[1,4]<-E_fk
  init[1,5]<-YD
  init[1,6]<-V_h

  firminit[,1]<-k
  firminit[,2]<-K
  firminit[,3]<-L
  firminit[,4]<-r_L
  firminit[,5]<-D_f
  firminit[,6]<-C
  firminit[,7]<-E_fc
  firminit[,8]<-yield*(r_d+delta)
  
  param[1,1]<-alpha1
  param[1,2]<-alpha2
  param[1,3]<-theta
  param[1,4]<-w
  param[1,5]<-delta
  param[1,6]<-r_d
  param[1,7]<-mu1
  param[1,8]<-mu2
  param[1,9]<-r_0
  param[1,10]<-iota1
  param[1,11]<-iota2
  param[1,12]<-lambda1
  param[1,13]<-kappa
  param[1,14]<-chi
  param[1,15]<-beta1
  param[1,16]<-beta2
  param[1,17]<-gamma
  param[1,18]<-expdyn
  param[1,19]<-opt
  param[1,20]<-pes
  param[1,21]<-epsilon
  param[1,22]<-eta
  param[1,23]<-rho
  param[1,24]<-tau
  param[1,25]<-lambda2
  param[1,26]<-gov
  param[1,27]<-phi_g
  param[1,28]<-phi_b1
  param[1,29]<-bank
  param[1,30]<-sigma
  param[1,31]<-omega
  param[1,32]<-fshare
  param[1,33]<-types1
  param[1,34]<-fulloutput
  param[1,35]<-CAR
  param[1,36]<-kappa_L
  param[1,37]<-divpol
  param[1,38]<-types2
  param[1,39]<-phi_b2
  param[1,40]<-phi_div
  
  return(list(init=init,param=param,firminit=firminit))
} 
