initnames=c("Y","E_b","D_h","E_fk","YD","V_h")
inits<-array(data=NA, dim=c(1,length(initnames)),dimnames = list(NULL,initnames))
parnames=c("alpha1","alpha2","psi","theta","w","delta","r_d","mu1","mu2","r_0","iota1","iota2","lambda1","kappa","chi","beta1","beta2","pi","gamma","expdyn","opt","pes","epsilon","eta","rho","tau","lambda2","gov","phi_g","u_n","phi_b","bank","sigma","omega","fshare","types","switch","beta","zeta1","zeta2","fulloutput")
params<-array(data=NA, dim=c(1,length(parnames)),dimnames = list(NULL,parnames))
nF=50
firminitnames=c("k","K","omega_c","L","r_L","share","D_f","C","E_fc","p_c","gamma","yield")
  
firminits<-array(data=NA,dim=c(nF,length(firminitnames)),dimnames=list(NULL,firminitnames))
init=function(init=inits,param=params,firminit=firminits){
  nF=50
  share<-c(rep(1/nF,nF))
  k_agg=10000
  k=k_agg*share
  w=1
  u=0.8
  kappa=0.25
  c=u*kappa*k_agg
  omega=0.5
  omega_c=omega
  p_k=(1+omega)*w
  K_agg=k_agg*p_k
  K=K_agg*share
  delta=0.025
  p_c=(1+omega)*w
  i_agg=delta*k_agg
  W_k=w*i_agg
  y=c+i_agg
  i=i_agg/nF
  c_dagg=c
  c_d=c_dagg*share
  Y=c_dagg*p_c+i_agg*p_k
  C=share*p_c*c_dagg
  N_dc=c_dagg
  W_cagg=N_dc*w
  W_c=W_cagg*share
  CF=C-W_c
  YD=c_dagg*p_c
  YD_e=YD
  Lev=0.4
  L_agg=Lev*K_agg
  L=share*L_agg
  r_0=0.01
  theta=0.025
  gamma=0.36
  int=i*p_k-theta*L+gamma*CF
  gap=C-W_c-theta*L-gamma*CF
  r_L=(gap-(int-gamma*CF))/L
  mu2=(-CF*r_0+CF*r_L)/((L-theta*L+p_k*i-(int-gamma*CF))*(r_L+theta))
  mu2=mean(mu2)
  Q=C-W_c
  CAR=0.05
  E_b=CAR*L_agg
  E_fk=0
  D=L_agg-E_b
  D_f=0.1*C
  D_h=D-sum(D_f)
  E_fc=K+D_f-L
  alpha1=0.85
  alpha2=(YD-alpha1*YD)/(D_h+E_b+sum(E_fc))
  V_h=D_h+sum(E_fc)+E_b
  lambda1=0.75
  iota1=-2.1
  iota2=1.1
  chi=0.75
  Div_b=mean(r_L)*sum(L)
  Div_fk=i_agg*p_k-W_k
  Pr_fc=C-W_c-i*p_k+(K-delta*k*p_k+i*p_k-K)-r_L*L
  Div_fc=Pr_fc
  pi=mean((Q-r_L*L)*4/K)
  beta1=0.4
  beta2=(beta1*mean((r_L*L+theta*L)/CF))/pi
  r_d=0.01
  rev=Q/delta
  yield=rev/(1+r_d/delta)
  p_ks=p_k+(1-(int-gamma*CF)/(i*p_k))*r_L/theta
  mu1=-((p_k+(1-(int-gamma*CF)/(i*p_k))*r_L/theta)*(k-delta*k)-yield)/((i*p_k)^2)
  p_dk=(yield-mu1*(i*p_k)^2)/(k-delta*k)
  p_dkint=(yield-mu1*(int-gamma*CF)^2)/(k-delta*k)
  mu1=mean(mu1)
  meanlev=mean(K/E_fc)
  expdyn=0
  opt=1.1
  pes=0.9
  epsilon=-1.3
  eta=-20
  rho=0.5
  tau=-58
  lambda2=0.38
  gov=0
  phi_g=2000
  u_n=u
  phi_b=0.2
  bank=0
  sigma=2.6
  fshare=1
  types=0
  psi=0.1
  switch=0
  beta=15
  zeta1=0.1
  zeta2=0.1
  fulloutput=1
    
  init[1,1]<-Y
  init[1,2]<-E_b
  init[1,3]<-D_h
  init[1,4]<-E_fk
  init[1,5]<-YD
  init[1,6]<-V_h

  firminit[,1]<-k
  firminit[,2]<-K
  firminit[,3]<-omega_c
  firminit[,4]<-L
  firminit[,5]<-r_L
  firminit[,6]<-share
  firminit[,7]<-D_f
  firminit[,8]<-C
  firminit[,9]<-E_fc
  firminit[,10]<-p_c
  firminit[,11]<-gamma
  firminit[,12]<-yield
  
  param[1,1]<-alpha1
  param[1,2]<-alpha2
  param[1,3]<-psi
  param[1,4]<-theta
  param[1,5]<-w
  param[1,6]<-delta
  param[1,7]<-r_d
  param[1,8]<-mu1
  param[1,9]<-mu2
  param[1,10]<-r_0
  param[1,11]<-iota1
  param[1,12]<-iota2
  param[1,13]<-lambda1
  param[1,14]<-kappa
  param[1,15]<-chi
  param[1,16]<-beta1
  param[1,17]<-beta2
  param[1,18]<-pi
  param[1,19]<-gamma
  param[1,20]<-expdyn
  param[1,21]<-opt
  param[1,22]<-pes
  param[1,23]<-epsilon
  param[1,24]<-eta
  param[1,25]<-rho
  param[1,26]<-tau
  param[1,27]<-lambda2
  param[1,28]<-gov
  param[1,29]<-phi_g
  param[1,30]<-u_n
  param[1,31]<-phi_b
  param[1,32]<-bank
  param[1,33]<-sigma
  param[1,34]<-omega
  param[1,35]<-fshare
  param[1,36]<-types
  param[1,37]<-switch
  param[1,38]<-beta
  param[1,39]<-zeta1
  param[1,40]<-zeta2
  param[1,41]<-fulloutput
  
  return(list(init=init,param=param,firminit=firminit))
} 
